// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// Firebase core configuration imports
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Provides pre-configured FirebaseOptions for different platforms
/// Used during Firebase initialization in main()
class DefaultFirebaseOptions {
  /// Dynamically selects the appropriate Firebase configuration
  /// based on the current platform (Android/iOS)
  static FirebaseOptions get currentPlatform {
    // Handle web platform exception
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }

    // Select configuration based on current platform
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // Handle unsupported platforms
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform - '
          'reconfigure using FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'Unsupported platform configuration',
        );
    }
  }

  /// Firebase configuration parameters for Android
  /// Contains sensitive authentication keys - keep secure
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCevpquuLJ0bYRuH66H2D5RyCJpsd2oXzc',
    appId: '1:686424720942:android:44e7d04b416ad6bcf201bf',
    messagingSenderId: '686424720942',
    projectId: 'fir-flutter-6399c',
    storageBucket: 'fir-flutter-6399c.firebasestorage.app',
  );

  /// Firebase configuration parameters for iOS
  /// Contains bundle identifier and iOS-specific keys
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD33y8Cvq4UbR60aLzQZrpF9S1mlTtmD1M',
    appId: '1:686424720942:ios:787409f232558dc9f201bf',
    messagingSenderId: '686424720942',
    projectId: 'fir-flutter-6399c',
    storageBucket: 'fir-flutter-6399c.fire basestorage.app',
    iosBundleId: 'com.example.fitness', // iOS bundle identifier for the app
  );
}
